import 'package:ddd_arch/core/resource/colors.dart';
import 'package:flutter/material.dart';

ThemeData lightTheme = ThemeData.light().copyWith(
  useMaterial3: true,
  brightness: Brightness.light,
  primaryColor: AppColors.primaryColorLight,
  scaffoldBackgroundColor: AppColors.backgroundColorLight,
  appBarTheme: AppBarTheme(
    color: AppColors.inversePrimaryColorLight,
    iconTheme: const IconThemeData(color: AppColors.iconColorLight),
    toolbarTextStyle: _lightTextTheme.bodyMedium,
    titleTextStyle: _lightTextTheme.titleLarge,
  ),
  iconTheme: const IconThemeData(
    color: AppColors.iconColorLight,
  ),
  textTheme: _lightTextTheme,
  dividerTheme: const DividerThemeData(
    color: AppColors.greyColor,
  ),
  textButtonTheme: TextButtonThemeData(
    style: TextButton.styleFrom(
      foregroundColor: AppColors.onTertiaryColorLight,
    ),
  ),
  colorScheme: colorSchemeLight,
);

ThemeData darkTheme = ThemeData.dark().copyWith(
    useMaterial3: true,
    brightness: Brightness.dark,
    primaryColor: AppColors.primaryColorDark,
    scaffoldBackgroundColor: AppColors.backgroundColorDark,
    appBarTheme: AppBarTheme(
      color: AppColors.outlineColorLight,
      iconTheme: const IconThemeData(color: AppColors.iconColorDark),
      toolbarTextStyle: _darkTextTheme.bodyMedium,
      titleTextStyle: _darkTextTheme.titleLarge,
    ),
    iconTheme: const IconThemeData(
      color: AppColors.iconColorDark,
    ),
    textTheme: _darkTextTheme,
    dividerTheme: const DividerThemeData(
      color: AppColors.greyColor,
    ),
    // colorScheme: const ColorScheme(
    //   brightness: Brightness.dark,
    //   primary: Colors.redAccent,
    //   onPrimary: Colors.white,
    //   secondary: Colors.orange,
    //   onSecondary: Colors.white,
    //   error: Colors.red,
    //   onError: Colors.white,
    //   background: Colors.black,
    //   onBackground: Colors.white,
    //   surface: Colors.green,
    //   onSurface: Colors.greenAccent,
    // ),
    colorScheme: colorSchemeDark);

const ColorScheme colorSchemeLight = ColorScheme(
  brightness: Brightness.dark,
  primary: AppColors.primaryColorLight,
  onPrimary: AppColors.onPrimaryColorLight,
  primaryContainer: AppColors.primaryContainerColorLight,
  onPrimaryContainer: AppColors.onPrimaryContainerColorLight,
  secondary: AppColors.secondaryColorLight,
  onSecondary: AppColors.onSecondaryColorLight,
  secondaryContainer: AppColors.secondaryContainerColorLight,
  onSecondaryContainer: AppColors.onSecondaryContainerColorLight,
  tertiary: AppColors.tertiaryColorLight,
  onTertiary: AppColors.onTertiaryColorLight,
  tertiaryContainer: AppColors.tertiaryContainerColorLight,
  onTertiaryContainer: AppColors.onTertiaryContainerColorLight,
  error: AppColors.errorColorLight,
  onError: AppColors.onErrorColorLight,
  errorContainer: AppColors.errorContainerColorLight,
  onErrorContainer: AppColors.onErrorContainerColorLight,
  background: AppColors.backgroundColorLight,
  onBackground: AppColors.onBackgroundColorLight,
  surface: AppColors.surfaceColorLight,
  onSurface: AppColors.onSurfaceColorLight,
  surfaceVariant: AppColors.surfaceVariantColorLight,
  onSurfaceVariant: AppColors.onSurfaceVariantColorLight,
  outline: AppColors.outlineColorLight,
  shadow: AppColors.shadowColorLight,
  inverseSurface: AppColors.inverseSurfaceColorLight,
  onInverseSurface: AppColors.onInverseSurfaceColorLight,
  inversePrimary: AppColors.inversePrimaryColorLight,
  surfaceTint: AppColors.surfaceTintColorLight,
);
const ColorScheme colorSchemeDark = ColorScheme(
  brightness: Brightness.dark,
  primary: AppColors.primaryColorDark,
  onPrimary: AppColors.onPrimaryColorDark,
  primaryContainer: AppColors.primaryContainerColorDark,
  onPrimaryContainer: AppColors.onPrimaryContainerColorDark,
  secondary: AppColors.secondaryColorDark,
  onSecondary: AppColors.onSecondaryColorDark,
  secondaryContainer: AppColors.secondaryContainerColorDark,
  onSecondaryContainer: AppColors.onSecondaryContainerColorDark,
  tertiary: AppColors.tertiaryColorDark,
  onTertiary: AppColors.onTertiaryColorDark,
  tertiaryContainer: AppColors.tertiaryContainerColorDark,
  onTertiaryContainer: AppColors.onTertiaryContainerColorDark,
  error: AppColors.errorColorDark,
  onError: AppColors.onErrorColorDark,
  errorContainer: AppColors.errorContainerColorDark,
  onErrorContainer: AppColors.onErrorContainerColorDark,
  background: AppColors.backgroundColorDark,
  onBackground: AppColors.onBackgroundColorDark,
  surface: AppColors.surfaceColorDark,
  onSurface: AppColors.onSurfaceColorDark,
  surfaceVariant: AppColors.surfaceVariantColorDark,
  onSurfaceVariant: AppColors.onSurfaceVariantColorDark,
  outline: AppColors.outlineColorDark,
  shadow: AppColors.shadowColorDark,
  inverseSurface: AppColors.inverseSurfaceColorDark,
  onInverseSurface: AppColors.onInverseSurfaceColorDark,
  inversePrimary: AppColors.inversePrimaryColorDark,
  surfaceTint: AppColors.surfaceTintColorDark,
);

TextTheme _lightTextTheme = const TextTheme(
  displayLarge: TextStyle(fontSize: 96, color: AppColors.textColorLight),
  displayMedium: TextStyle(fontSize: 60, color: AppColors.textColorLight),
  displaySmall: TextStyle(fontSize: 48, color: AppColors.textColorLight),
  headlineLarge: TextStyle(fontSize: 42, color: AppColors.textColorLight),
  headlineMedium: TextStyle(fontSize: 34, color: AppColors.textColorLight),
  headlineSmall: TextStyle(fontSize: 24, color: AppColors.textColorLight),
  titleLarge: TextStyle(
    fontSize: 20,
    color: AppColors.textColorLight,
    fontWeight: FontWeight.w500,
  ),
  titleMedium: TextStyle(fontSize: 16, color: AppColors.textColorLight),
  titleSmall: TextStyle(
    fontSize: 14,
    color: AppColors.textColorLight,
    fontWeight: FontWeight.w500,
  ),
  bodyLarge: TextStyle(fontSize: 16, color: AppColors.textColorLight),
  bodyMedium: TextStyle(fontSize: 14, color: AppColors.textColorLight),
  bodySmall: TextStyle(fontSize: 12, color: AppColors.textColorLight),
  labelLarge: TextStyle(
    fontSize: 14,
    color: AppColors.textColorLight,
    fontWeight: FontWeight.w500,
  ),
  labelSmall: TextStyle(fontSize: 14, color: AppColors.textColorLight),
);

TextTheme _darkTextTheme = const TextTheme(
  displayLarge: TextStyle(fontSize: 96, color: AppColors.textColorDark),
  displayMedium: TextStyle(fontSize: 60, color: AppColors.textColorDark),
  displaySmall: TextStyle(fontSize: 48, color: AppColors.textColorDark),
  headlineMedium: TextStyle(fontSize: 34, color: AppColors.textColorDark),
  headlineSmall: TextStyle(fontSize: 24, color: AppColors.textColorDark),
  titleLarge: TextStyle(
    fontSize: 20,
    color: AppColors.textColorDark,
    fontWeight: FontWeight.w500,
  ),
  titleMedium: TextStyle(fontSize: 16, color: AppColors.textColorDark),
  titleSmall: TextStyle(
    fontSize: 14,
    color: AppColors.textColorDark,
    fontWeight: FontWeight.w500,
  ),
  bodyLarge: TextStyle(fontSize: 16, color: AppColors.textColorDark),
  bodyMedium: TextStyle(fontSize: 14, color: AppColors.textColorDark),
  bodySmall: TextStyle(fontSize: 12, color: AppColors.textColorDark),
  labelLarge: TextStyle(
    fontSize: 14,
    color: AppColors.textColorDark,
    fontWeight: FontWeight.w500,
  ),
  labelSmall: TextStyle(fontSize: 14, color: AppColors.textColorDark),
);
